# Generated by Django 4.0.4 on 2022-04-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infocenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_text', models.CharField(blank=True, max_length=30, null=True)),
                ('info_name', models.CharField(blank=True, max_length=20, null=True)),
                ('info_subject', models.CharField(blank=True, max_length=30, null=True)),
                ('info_item', models.ImageField(blank=True, null=True, upload_to='photo1')),
                ('info_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
