# Generated by Django 4.0.4 on 2022-04-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zefir_mall_app', '0004_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='photo1')),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rent',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='pp',
            field=models.ImageField(blank=True, null=True, upload_to='photo1'),
        ),
    ]
