# Generated by Django 4.0.4 on 2022-04-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zefir_mall_app', '0005_footer_rent_email_rent_number_rent_pp'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodcort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
