# Generated by Django 4.0.4 on 2022-04-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zefir_mall_app', '0006_foodcort'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcort',
            name='foodlink',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='foodcort',
            name='foodphoto',
            field=models.ImageField(blank=True, null=True, upload_to='photo1'),
        ),
    ]
