# Generated by Django 4.0.4 on 2022-04-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zefir_mall_app', '0007_foodcort_foodlink_foodcort_foodphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
