# Generated by Django 4.0.4 on 2022-04-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zefir_mall_app', '0008_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_link',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo1'),
        ),
    ]
