# Generated by Django 4.0.4 on 2022-04-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zefir_mall_app', '0009_company_company_link_company_company_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
